[general]
allow-move-request = true
allow-resize-request = true
allow-fullscreen-request = true

[[window-rules]]
decoration = "server_side"
border = { width = 2, color = "6b6b6b" }

[[window-rules]]
matches = [{ is-focused = true }]
border = { width = 2, color = "6a9fb5" }

[[window-rules]]
matches = [{ is-floating = true }]
decoration = "client_side"

[[window-rules]]
matches = [{ is-maximized = true }]
border = { width = 2, color = "a17e4d" }

[[window-rules]]
matches = [{ is-swap-source = true }]
border = { width = 2, color = "ac4242" }

[[window-rules]]
matches = [{ is-swap-target = true }]
border = { width = 2, color = "90a959" }
opacity = 0.8

[layouts]
master = { nodes = [{ ratio = 1.5 }, { layout = "slaves" }] }
slaves = { split = "horizontal", nodes = [{ repeat = 3 }] }
default = "master"
# main = { nodes = [{ layout = "sub", repeat = 2 }] }
# sub = { split = "horizontal", nodes = [{ repeat = 2 }] }
# default = "main"

[key]
repeat-delay = 200
repeat-rate = 25

[key.bindings]
"alt+page_up" = { action = "prev_workspace" }
"alt+page_down" = { action = "next_workspace" }
"alt+1" = { action = "switch_workspace", name = 1 }
"alt+2" = { action = "switch_workspace", name = 2 }
"alt+3" = { action = "switch_workspace", name = 3 }
"alt+4" = { action = "switch_workspace", name = 4 }
"alt+5" = { action = "switch_workspace", name = 5 }
"alt+shift+1" = { action = "move_to_workspace", name = 1 }
"alt+shift+2" = { action = "move_to_workspace", name = 2 }
"alt+shift+3" = { action = "move_to_workspace", name = 3 }
"alt+shift+4" = { action = "move_to_workspace", name = 4 }
"alt+shift+5" = { action = "move_to_workspace", name = 5 }
"alt+ctrl+1" = { action = "move_to_workspace", name = 1, focus = false }
"alt+ctrl+2" = { action = "move_to_workspace", name = 2, focus = false }
"alt+ctrl+3" = { action = "move_to_workspace", name = 3, focus = false }
"alt+ctrl+4" = { action = "move_to_workspace", name = 4, focus = false }
"alt+ctrl+5" = { action = "move_to_workspace", name = 5, focus = false }
"alt+h" = { action = "focus_window", direction = "left" }
"alt+j" = { action = "focus_window", direction = "bottom" }
"alt+k" = { action = "focus_window", direction = "top" }
"alt+l" = { action = "focus_window", direction = "right" }
"alt+shift+h" = { action = "swap_window", direction = "left" }
"alt+shift+j" = { action = "swap_window", direction = "bottom" }
"alt+shift+k" = { action = "swap_window", direction = "top" }
"alt+shift+l" = { action = "swap_window", direction = "right" }
"alt+ctrl+h" = { action = "resize_window", direction = "left", unit = "50px" }
"alt+ctrl+j" = { action = "resize_window", direction = "bottom", unit = "50px" }
"alt+ctrl+k" = { action = "resize_window", direction = "top", unit = "50px" }
"alt+ctrl+l" = { action = "resize_window", direction = "right", unit = "50px" }
"alt+space" = { action = "toggle_floating" }
"alt+shift+space" = { action = "toggle_floating_hidden" }
"alt+m" = { action = "toggle_maximize" }
"alt+f" = { action = "toggle_fullscreen" }
"alt+q" = { action = "close_window" }
"alt+return" = { action = "execute", command = ["alacritty"] }
"alt+a" = { action = "assistant" }

[pointer.bindings]
"alt+btn_left" = "move"
"alt+btn_right" = "resize"

[pointer]
resize-at = "edge_or_corner"

[assistant]
enable = false
save-layout-after = 10
