[package]
name = "loomwm"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["assistant"]

[dependencies]
assistant = { path = "./assistant" }
anyhow.workspace = true
bitflags = { version = "2.10.0", features = ["serde", "std"] }
evdev = "0.13.2"
notify = "8.2.0"
regex = "1.12.3"
serde.workspace = true
slotmap = "1.1.1"
smithay = { version = "0.7.0", default-features = false, features = [
  "backend_winit",
  "wayland_frontend",
  "desktop",
  "renderer_gl",
] }
toml = "0.9.11"
xkbcommon = "0.9.0"
serde_json.workspace=true
burn.workspace= true

[workspace.dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
burn = { version = "0.20.1", features = ["train", "wgpu", "ndarray"] }

[dev-dependencies]
test-case = "3.3.1"
