[package]
name = "loomwm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bitflags = "2.10.0"
evdev = "0.13.2"
slotmap = "1.1.1"
smithay = { version = "0.7.0", default-features = false, features = [
  "backend_winit",
  "wayland_frontend",
  "desktop",
  "renderer_gl",
] }

[dev-dependencies]
proptest = "1.9.0"
test-case = "3.3.1"
