words = [
    "alacritty",
    "batcher",
    "bbox",
    "ints",
    "keysym",
    "mappeds",
    "shm",
    "smithay",
    "toplevel",
    "unconstrain",
    "unfullscreen",
    "vecs",
    "wgpu",
    "winit",
    "xdg",
]
